image: phpunit/phpunit:latest

pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install libxslt-dev -y
          - docker-php-ext-install xsl && docker-php-ext-enable xsl
          - composer self-update
          - composer install
          - phpunit --coverage-text --configuration phpunit.xml.dist
