image: phpunit/phpunit:5.0.3

pipelines:
  default:
    - step:
        script:
          - docker-php-ext-install xsl
          - php --version
          - composer --version
          - phpunit --version
          - composer self-update
          - composer install
          - phpunit --coverage-text --configuration phpunit.xml.dist
