image: veridu/php-ci:latest

pipelines:
  default:
    - step:
        script:
          - cat phinx.yml.dist | sed s/veridu-api/test/ > phinx.yml
          - cat config/testing.php.dist | sed s/veridu-api/test/ > config/testing.php
          - composer self-update
          - composer install
          - service postgresql start
          - ./vendor/bin/phpunit --coverage-text --configuration phpunit.xml.dist
