image: composer/composer:latest

pipelines:
  default:
    - step:
        script:
          - apt-get update
          - apt-get install libxml-dev libxml
          - docker-php-ext-install xsl
          - docker-php-ext-enable xsl
          - composer self-update
          - composer install
          - phpunit --coverage-text --configuration phpunit.xml.dist
