<?php
/**
 * Copyright (c) 2012-2016 Veridu Ltd <https://veridu.com>
 * All rights reserved.
 */

namespace App\Entity;

use App\Helper\Utils;

/**
 * Credentials Entity.
 *
 * @apiEntity Credential
 * @apiEntityRequiredProperty int company_id Company owner of the Credential
 * @apiEntityRequiredProperty string name Credential's name
 * @apiEntityProperty string slug Slug based on credential's name
 * @apiEntityProperty string public Credential's public key, generated by the API
 * @apiEntityProperty string private Credential's private key, generated by the API
 * @apiEntityProperty string production Says whether the Credential is a productio credential or a development credential, defaults to false
 *
 * @property int $id
 * @property string company_id
 * @property string name
 * @property string slug
 * @property string public
 * @property string private
 * @property string production
 * @property string $created_at
 * @property string $updated_at
 */
class Credential extends AbstractEntity {
    /**
     * {@inheritdoc}
     */
    protected $visible = ['name', 'slug', 'public_key', 'created_at'];

    public function setNameAttribute($value) {
        $this->attributes['name'] = $value;
        $this->attributes['slug'] = Utils::slugify($value);
    }
}
